services:
  postgres:
    container_name: postgres
    image: postgis/postgis:14-master
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  controller:
    container_name: controller
    image: hasura/graphql-engine:v2.40.2
    ports:
      - "8080:8080"
    volumes:
      - ./controller/migrations:/hasura-migrations
      - ./controller/metadata:/hasura-metadata
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  go-backend:
    container_name: go-backend
    build: ./go-backend
    ports:
      - 3000:3000
    environment:
      DB_POSTGRES_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      SECRET: 3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R
      TOKEN_EXPIRATION: 600
    depends_on:
      - postgres
volumes:
  db_data:
